#!/usr/bin/env bash
# Install mkmlab.space nginx site on Hostinger VPS (same host as jemaai / no1kmedi).
set -euo pipefail

SITE_NAME="mkmlab.space"
AVAIL="/etc/nginx/sites-available/${SITE_NAME}"
ENABLED="/etc/nginx/sites-enabled/${SITE_NAME}"
ROOT="/var/www/mkmlab"

DO_APPLY=0
if [[ "${1:-}" == "-y" ]] || [[ "${1:-}" == "--apply" ]]; then
  DO_APPLY=1
  shift
fi

mkdir -p "$ROOT"
tee "$AVAIL" >/dev/null <<'EOF'
# mkm mkmlab.space static (generated by apply_mkmlab_space_nginx_v1.sh)
server {
    listen 80;
    listen [::]:80;
    server_name mkmlab.space www.mkmlab.space;
    root /var/www/mkmlab;
    index index.html en.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

ln -sf "$AVAIL" "$ENABLED"
echo "Linked $ENABLED -> $AVAIL"
echo "Ensure docroot has index.html: $ROOT"

if [[ "$DO_APPLY" == "1" ]]; then
  nginx -t
  systemctl reload nginx
  echo "nginx reloaded"
else
  echo "Dry-run: run with -y to nginx -t && reload"
fi
