#!/usr/bin/env python3
"""Execute evidence follow-up actions generated by fusion gate."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
TODO = ROOT / "reports" / "constitution" / "btrack_pilot" / "fusion_gate_evidence_todo_latest.json"
OUT = ROOT / "reports" / "constitution" / "btrack_pilot" / "fusion_gate_evidence_followup_latest.json"


def _run(cmd: list[str]) -> dict[str, Any]:
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    return {
        "command": cmd,
        "exit_code": proc.returncode,
        "stdout_tail": (proc.stdout or "")[-1000:],
        "stderr_tail": (proc.stderr or "")[-1000:],
    }


def _jread(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    ap = argparse.ArgumentParser(description="Execute fusion gate evidence todo")
    ap.add_argument("--todo", default=str(TODO))
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--python", default=sys.executable)
    ap.add_argument(
        "--include-shared-vault",
        action="store_true",
        help="Include shared vault docs while building DSS enriched jsonl.",
    )
    args = ap.parse_args()

    todo_path = Path(args.todo)
    out_path = Path(args.out)
    if not todo_path.is_absolute():
        todo_path = ROOT / todo_path
    if not out_path.is_absolute():
        out_path = ROOT / out_path
    if not todo_path.is_file():
        print(f"ERROR: missing todo file: {todo_path}")
        return 2

    todo = _jread(todo_path)
    py = args.python
    dss_build_cmd = [py, "scripts/build_btrack_dss_enriched_from_docs.py"]
    if args.include_shared_vault:
        dss_build_cmd.append("--include-shared-vault")
    steps = [
        dss_build_cmd,
        [py, "scripts/extract_btrack_symbol_candidates.py", "--top-k", "1000"],
        [py, "scripts/curate_btrack_symbol_candidates.py", "--top-k", "200", "--min-dss-quota", "20", "--min-curated-count", "20"],
        [py, "scripts/build_deut32_dss_lexicon_from_enriched.py", "--min-source-doc-support", "2"],
        [py, "scripts/report_semantic_gap_analysis.py", "--dss-lexicon", "reports/constitution/btrack_pilot/dss_variant_lexicon_deut32_8_auto_latest.json", "--per-token-cap-ratio", "0.35"],
        [py, "scripts/run_btrack_fusion_gate.py", "--max-cee-risk-band", "critical_thin"],
    ]

    run_logs: list[dict[str, Any]] = []
    for cmd in steps:
        log = _run(cmd)
        run_logs.append(log)
        if log["exit_code"] != 0:
            break

    success = all(int(x["exit_code"]) == 0 for x in run_logs)
    followup = {
        "schema": "fusion_gate_evidence_followup_v1",
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "todo_path": str(todo_path),
        "todo_risk_band": todo.get("risk_band"),
        "todo_thin_margin_streak": todo.get("thin_margin_streak"),
        "success": success,
        "steps": run_logs,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(followup, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"out={out_path}")
    print(f"success={success}")
    return 0 if success else 1


if __name__ == "__main__":
    raise SystemExit(main())
