"""Dev OS LTM graph concepts — Packaging + Fuel ([HYPO] / B-track routing)."""

from __future__ import annotations

from mkm_long_term_memory_graph_lib_v1 import ConceptSpec, CoordinateSpec

DEV_OS_CONCEPT_SPECS: tuple[ConceptSpec, ...] = (
    ConceptSpec(
        concept_id="git_hygiene_internal_first",
        label_ko="Git hygiene · internal-first push",
        essence="1작업=1브랜치=1PR · 기본 push-internal/gitea · origin no_push",
        must_keep_tags=("push-internal", "1작업"),
        query_aliases=("git", "push", "gitea", "internal", "worktree", "pr", "remote publication"),
        field_tags=("packaging", "git", "governance", "fact_lock"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="AGENTS.md",
                anchor_start="## Git · 원격",
                anchor_end="## User Rules",
            ),
        ),
        related_concepts=("remote_publication_github_explicit", "verify_p0_constitution_paths"),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="remote_publication_github_explicit",
        label_ko="GitHub push · explicit acknowledge only",
        essence="Push-GitHub-Explicit -Acknowledge 예외만 · public mirror 기본 차단",
        must_keep_tags=("Push-GitHub-Explicit.ps1", "Acknowledge"),
        query_aliases=("github", "origin", "hq", "no_push", "public mirror", "explicit push"),
        field_tags=("packaging", "git", "governance", "security"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="AGENTS.md",
                anchor_start="## Git · 원격",
                anchor_end="## User Rules",
            ),
        ),
        related_concepts=("git_hygiene_internal_first",),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="athena_ecc_execution_governance",
        label_ko="Athena ECC · athena_run_v1 §28",
        essence="TRADE_EXECUTE+HOLD → DENIED exit2 · DPAPI --target · ecc_execution_clearance_latest.json",
        must_keep_tags=("ECC DENIED", "execution_clearance_certificate_v1"),
        query_aliases=("athena_run", "ecc", "execution governance", "dpapi", "trade_execute", "§28"),
        field_tags=("packaging", "governance", "ecc", "fact_lock"),
        priority=9,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="docs/final/CONSTITUTION_INFERENCE_IMPLEMENTATION_FACTS.md",
                anchor_start="## 28) 실행 거버넌스",
                anchor_end="**명시적 한계(우회):**",
            ),
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/athena_run_v1.py",
                anchor_start="SCHEMA_ECC =",
                anchor_end="FAKE_BINANCE_KEY",
            ),
        ),
        related_concepts=(
            "integrated_governance_ecc_input",
            "verify_p0_constitution_paths",
            "trading_go_nogo_status_ssot",
        ),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="raw_repair_dual_reporting",
        label_ko="Raw/Repair dual reporting · repair≠core",
        essence="raw+repair_v2 동시 보고 · repair-only Track A 승격 금지",
        must_keep_tags=("repair_v2", "repair_v2_minus_raw"),
        query_aliases=("raw", "repair", "dual reporting", "alignment_pass_rate", "operational post-processor"),
        field_tags=("packaging", "compression", "fact_lock", "ms"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path=".cursor/rules/raw-repair-dual-reporting-v1.mdc",
                anchor_start="## Always",
                anchor_end="## Never",
            ),
        ),
        related_concepts=("compression_fail_comp004_boundary", "compression_track_a_active_kpi"),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="public_facing_ip_copy_v17",
        label_ko="PUBLIC_FACING v1.7 · 대외 카피 게이트",
        essence="웹·제안서·쇼룸 카피 SSOT — 과장·비밀·Track A KPI 헤드라인 금지",
        must_keep_tags=("v1.7", "Public-facing"),
        query_aliases=("public facing", "copy", "ip", "proposal", "showroom", "marketing", "면책"),
        field_tags=("packaging", "track_c", "governance", "copy"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="docs/final/PUBLIC_FACING_SECURITY_AND_IP_COPY_CHECKLIST_V1.md",
                anchor_start="# Public-facing security",
                anchor_end="## 1) Security",
            ),
        ),
        related_concepts=("send_gate_hold_doctrine", "design_showroom_domain_portfolio"),
        lane_hint="design",
    ),
    ConceptSpec(
        concept_id="mkm_orchestrator_todo_queue",
        label_ko="MKM Orchestrator · todo_queue mechanical",
        essence="todo_queue_latest.json 기계 실행 — B→A·live auto-merge 없음",
        must_keep_tags=("todo_queue_v1", "task_queue_ssot"),
        query_aliases=("orchestrator", "todo queue", "daemon", "continuous", "mechanical"),
        field_tags=("packaging", "orchestrator", "governance", "btrack"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="json_pointer",
                file_path="docs/final/artifacts/mkm_orchestrator_connection_spec_v1.json",
                json_pointers=("/schema_version", "/task_queue_ssot/schema_path"),
            ),
        ),
        related_concepts=("ltm_graph_self_meta",),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="verify_p0_constitution_paths",
        label_ko="P0 path gate · verify_p0",
        essence="verify_p0_constitution_gate_paths.ps1 — 필수 경로 존재 exit0 = SSOT anchor",
        must_keep_tags=("P0 path gate", "every entry must exist"),
        query_aliases=("p0", "verify_p0", "constitution paths", "path gate", "fact-lock bundle"),
        field_tags=("packaging", "fact_lock", "constitution", "p0"),
        priority=9,
        coordinates=(
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/verify_p0_constitution_gate_paths.ps1",
                anchor_start="# P0 path gate:",
                anchor_end="$required = @(",
            ),
        ),
        related_concepts=("fact_lock_implementation", "run_fact_lock_bundle_entry"),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="track_a_active_report_human_gate",
        label_ko="MULTILENS active report · human sign-off",
        essence="MULTILENS_ULTRA_COMPRESSION_ACTIVE_REPORT overwrite — human sign-off 없으면 금지",
        must_keep_tags=("human", "sign-off", "MULTILENS_ULTRA_COMPRESSION_ACTIVE_REPORT"),
        query_aliases=("active report", "multilens overwrite", "golden 40", "would_change_active"),
        field_tags=("packaging", "compression", "track_a", "ms"),
        priority=9,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path=".cursor/rules/mkm-cognitive-architecture-v1.mdc",
                anchor_start="## NEVER (FAIL-COMP-004)",
                anchor_end="## OPTIONAL",
            ),
        ),
        related_concepts=("compression_track_a_active_kpi", "compression_fail_comp004_boundary"),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="integrated_governance_ecc_input",
        label_ko="Integrated governance · ECC input SSOT",
        essence="integrated_governance_v1_latest.json — final_regime·veto_reason_codes → athena_run",
        must_keep_tags=("integrated_governance_v1", "final_regime", "veto_reason_codes"),
        query_aliases=("integrated governance", "final_action_allowed", "ecc input", "regime attack"),
        field_tags=("packaging", "governance", "ecc", "oracle"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="json_pointer",
                file_path="docs/final/artifacts/integrated_governance_v1_latest.json",
                json_pointers=("/schema", "/final_regime", "/veto_reason_codes"),
            ),
        ),
        related_concepts=("athena_ecc_execution_governance",),
        lane_hint="oracle",
    ),
    ConceptSpec(
        concept_id="cursor_cloud_sandbox_boundary",
        label_ko="Cursor Cloud/Sandbox · live key 금지",
        essence="Cloud Agent=검증·PR 초안 · 실매매·VPS·DPAPI 키 주입 금지",
        must_keep_tags=("Cloud Agent", "실매매", "프로덕션 키 금지"),
        query_aliases=("cloud agent", "sandbox", "cursor cloud", "dev environment", "dockerfile"),
        field_tags=("packaging", "cursor", "governance", "security"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path=".cursor/rules/cursor-cloud-sandbox-boundary.mdc",
                anchor_start="## Role map",
                anchor_end="## Cursor 3.4",
            ),
        ),
        related_concepts=("local_vps_one_rule_workflow",),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="compression_send_prep_scaffold",
        label_ko="SEND prep scaffold · HOLD until counsel",
        essence="Invoke-CompressionSendPrepScaffold — masked JSONL stub · ready_for_external_send false",
        must_keep_tags=("SEND prep scaffold", "SEND_GATE stays HOLD"),
        query_aliases=("send prep", "compression send", "masked jsonl", "counsel", "external send"),
        field_tags=("packaging", "send_gate", "compression", "ms"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/Invoke-CompressionSendPrepScaffold_v1.ps1",
                anchor_start="SEND prep scaffold:",
                anchor_end='Write-Host "=== SEND prep scaffold',
            ),
        ),
        related_concepts=("send_gate_hold_doctrine", "ms_lane_submission_hold"),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="compression_openapi_v1_stub_contract",
        label_ko="OpenAPI v1 stub · compress/expand/metering",
        essence="openapi_token_compression_stub_v1.yaml — POST /v1/compress · /v1/metering/log",
        must_keep_tags=("/v1/compress", "/v1/metering/log"),
        query_aliases=("openapi v1", "compression api", "token compression", "stub contract", "8010"),
        field_tags=("fuel", "compression", "api", "openapi"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="docs/final/openapi_token_compression_stub_v1.yaml",
                anchor_start="- POST /v1/compress:",
                anchor_end="Auth, rate limits",
            ),
        ),
        related_concepts=("compression_token_api_v1_stub", "track_a_metering_log_endpoint"),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="compression_token_api_v1_stub",
        label_ko="compression_token_api_stub.py · FastAPI v1",
        essence="FastAPI stub — domain router · hydrate_metrics · expand echo",
        must_keep_tags=("track_a_metering_log_v1", "metering/log"),
        query_aliases=("compression_token_api_stub", "fastapi compress", "8010", "hydrate_metrics"),
        field_tags=("fuel", "compression", "api", "implementation"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/compression_token_api_stub.py",
                anchor_start='@app.post("/v1/metering/log"',
                anchor_end='@app.post("/v1/compress"',
            ),
        ),
        related_concepts=("compression_openapi_v1_stub_contract",),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="compression_openapi_v2_draft",
        label_ko="OpenAPI v2 draft · Trust Packet",
        essence="v2 compression_packet · evaluate_report path · B-track COMP-ATOM-05",
        must_keep_tags=("Trust Packet", "compression_packet"),
        query_aliases=("openapi v2", "trust packet", "v2 compress", "8011", "comp-atom"),
        field_tags=("fuel", "compression", "api", "btrack"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="docs/final/openapi_token_compression_v2_draft.yaml",
                anchor_start="title: MKM Token Compression API (v2 draft",
                anchor_end="paths:",
            ),
        ),
        related_concepts=("compression_openapi_v1_stub_contract",),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="stt_routing_audit_log_schema",
        label_ko="STT routing audit log v1 schema",
        essence="Silver/hybrid STT route audit row — B-track until product wiring",
        must_keep_tags=("stt_routing_audit_log_v1", "schema_version"),
        query_aliases=("stt", "routing audit", "silver tech", "pii_redaction", "audit log"),
        field_tags=("fuel", "schema", "stt", "track_c"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="json_pointer",
                file_path="docs/final/schemas/stt_routing_audit_log_v1.schema.json",
                json_pointers=("/properties/schema_version/const", "/required"),
            ),
        ),
        related_concepts=("public_facing_ip_copy_v17",),
        lane_hint="design",
    ),
    ConceptSpec(
        concept_id="track_a_metering_log_endpoint",
        label_ko="Track A metering · POST /v1/metering/log",
        essence="append-only JSONL metering · TRACK_A_METERING_LOG_PATH env override",
        must_keep_tags=("TRACK_A_METERING_LOG_PATH", "meter_schema"),
        query_aliases=("metering", "meter log", "token_in", "commercialization daily", "band gate"),
        field_tags=("fuel", "track_a", "metering", "compression"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/compression_token_api_stub.py",
                anchor_start="TRACK_A_METERING_LOG_PATH",
                anchor_end="def metering_log",
            ),
        ),
        related_concepts=("compression_openapi_v1_stub_contract", "p0_commercialization_tracker"),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="run_fact_lock_bundle_entry",
        label_ko="Fact-Lock bundle · run_fact_lock_bundle.ps1",
        essence="로컬 CI-parity pytest 번들 — dual-regime-integrity 정렬",
        must_keep_tags=("Fact-Lock 번들", "dual-regime-integrity"),
        query_aliases=("fact lock bundle", "athena bundle", "persona athena", "run_fact_lock"),
        field_tags=("fuel", "fact_lock", "pytest", "p0"),
        priority=8,
        coordinates=(
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/run_fact_lock_bundle.ps1",
                anchor_start=".SYNOPSIS",
                anchor_end=".DESCRIPTION",
            ),
        ),
        related_concepts=("verify_p0_constitution_paths", "run_workspace_automation_health"),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="run_workspace_automation_health",
        label_ko="Automation health · amsaeng default chain",
        essence="run_workspace_automation_health.ps1 — P0·reconcile·선택 스모크 허브",
        must_keep_tags=("IncludeCompressionKpi", "IncludeFallbackTriggerTelemetry"),
        query_aliases=("automation health", "amsaeng", "workspace health", "persona health"),
        field_tags=("fuel", "infra", "health", "automation"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="file_excerpt",
                file_path="scripts/run_workspace_automation_health.ps1",
                anchor_start="IncludeCompressionKpi",
                anchor_end="IncludeLiteralTrack",
            ),
        ),
        related_concepts=("run_fact_lock_bundle_entry",),
        lane_hint="infra",
    ),
    ConceptSpec(
        concept_id="prism_grand_index_registry",
        label_ko="Prism Grand Index · logical path registry",
        essence="MKM12_PRISM_INDEX_REGISTRY — 논리 색인(코드 4D≠) · CONSTITUTION §14",
        must_keep_tags=("mkm12_prism_index_registry_v1", "Grand Indexing"),
        query_aliases=("prism", "grand index", "prism_id", "registry", "§14"),
        field_tags=("fuel", "prism", "index", "resume"),
        priority=6,
        coordinates=(
            CoordinateSpec(
                kind="json_pointer",
                file_path="docs/final/MKM12_PRISM_INDEX_REGISTRY_V1.json",
                json_pointers=("/schema", "/description"),
            ),
        ),
        related_concepts=("fact_lock_implementation", "ltm_graph_self_meta"),
    ),
    ConceptSpec(
        concept_id="p0_commercialization_tracker",
        label_ko="P0 commercialization tracker · bench order",
        essence="상용화 순서·LLM tier·증거 경로 — bench before live",
        must_keep_tags=("Bench(모의·테스트) 기본", "팩트 SSOT"),
        query_aliases=("p0 tracker", "commercialization", "bench first", "llm tier", "상용화"),
        field_tags=("fuel", "p0", "commercialization", "governance"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="markdown_anchor",
                file_path="docs/final/P0_COMMERCIALIZATION_TRACKER.md",
                anchor_start="## 원칙",
                anchor_end="### 권장 작업 순서",
            ),
        ),
        related_concepts=("track_a_metering_log_endpoint", "verify_p0_constitution_paths"),
        lane_hint="ms",
    ),
    ConceptSpec(
        concept_id="independent_lens_shadow_gate",
        label_ko="Independent lens shadow gate · observation_only",
        essence="a_track_binding forbidden · consensus shadow — non-gating advisory",
        must_keep_tags=("independent_lens_shadow_gate_v1", "a_track_binding"),
        query_aliases=("independent lens", "shadow gate", "consensus", "observation_only", "fusion shadow"),
        field_tags=("fuel", "lens", "oracle", "btrack"),
        priority=7,
        coordinates=(
            CoordinateSpec(
                kind="json_pointer",
                file_path="docs/final/artifacts/independent_lens_shadow_gate_latest.json",
                json_pointers=("/schema", "/policy/a_track_binding", "/policy/recommended_mode"),
            ),
        ),
        related_concepts=("lens_logos_non_gating_pack", "prophecy_research_only_boundary"),
        lane_hint="oracle",
    ),
)
