param(
    [string]$WorkspaceRoot = "C:\workspace"
)

try {
    $WorkspaceRoot = (Resolve-Path -LiteralPath $WorkspaceRoot).Path
}
catch {
    Write-Host "FAIL: WorkspaceRoot not found or not accessible: $WorkspaceRoot" -ForegroundColor Red
    exit 1
}

# P0 path gate: every entry must exist in the workspace. Prune when files are not
# in this clone; re-add from main when those scripts return. (Track A metering
# multiline, kospi WF verify, etc. were removed 2026-04-18 for local pass.)
# 2026-04-30: join walkforward + fixtures; dedupe news schema block.
# 2026-05-02: Track B 명리 지휘관 리포트 봉투 (envelope JSON, build script, pytest).
# 2026-05-02: macro stub eval + manseryeok bot fusion fields (eval script, stub pytest).
# 2026-05-02: 起運 qiyun v1 (solar_term_jie_crossings, myeongri_qiyun_v1, pytest).
# 2026-05-02: Logos Track B commander deep report v1 + shared track_b_commander_gate_v1.
# 2026-05-02: Market Sasang lens v1 (policy, engine, runner, schema, contract, pytest).
# 2026-05-02: Sasang interpretive insight bundle v1.1 (interpretive_depth_ko + synthesis_v1, schema, contract, pytest).
# 2026-05-02: run_fact_lock_bundle.ps1 (Fact-Lock 번들; dual-regime 정렬 사상 통찰 pytest 포함).
# 2026-05-02: MKM_LENS_GLOBAL_PROFILE_PROMPT_RAG_INSTRUCTIONS_DRAFT_V1.md (B-track NL 번역층 초안).
# 2026-05-02: Logos vector ANN lite v1 (hash_stub SQLite report; sqlite+json artifact gitignored).
# 2026-05-02: M5 rule_school_mkm_4d_v1 (policy JSON, loader/blend, pytest).
# 2026-05-02: M2–M4 myeongni (jijangan ohang weights, daewoon v1, jijangan ohang script, daewoon test).
# 2026-05-02: +4 myeongni jijangan LUT M1 (lut, schema, script, test).
# 2026-05-05: JEMA_AI_DOMAIN_POINTER_V1.md (jema-ai.com 도메인 포인터; P0 존재 게이트).
# 2026-05-05: MKM_DOMAIN_PORTFOLIO_POINTER_V1.md (도메인×역할×쇼룸 배치 §1.1; P0 존재 게이트).
# 2026-05-05: TRACK_C_IP_BUSINESS_PLAN_2026-04-17.md (Track C 상용·법무·IP 경계 SSOT; P0 존재 게이트).
# 2026-05-05: PUBLIC_FACING_SECURITY_AND_IP_COPY_CHECKLIST_V1.md (대외 문서·홈·쇼룸 보안·IP 카피 체크리스트; P0 존재 게이트).
# 2026-05-05: MKM_HEALTH_WELLNESS_COPY_GUARDRAILS_KR_V1.md (KR 건강·웰빙 대외 카피 가드레일; P0 존재 게이트).
# 2026-05-05: CENTRAL_AGENT_MEMORY_V1.md (명리 렌즈 고도화 v1 등 장기기억 지문; P0 존재 게이트).
# 2026-05-05: 명리 core vector v1 schema/test (지장간 배율 엔진 Sprint-1 base vector lock).
# 2026-05-05: 명리 daewoon timeline v1 schema/test (Sprint-2 time regime lock).
# 2026-05-05: Yang(2015) 표면 8자 B-track 스키마·벤치·P0 경로 (btrack_yang / celebrity benchmark / saju birth / v2 upgrade).
# 2026-05-02: 일일 실행 인사이트 브리프 v1 (§1c 독립 렌즈·CONSTITUTION §3.3 행; 산출 JSON은 게이트 목록 미포함).
# 2026-05-10: VPS L1 bench one-click script (pair with BENCH_L1_API_LOAD_VPS_RUNBOOK.md).
# 2026-05-02: 압축 주간 거버넌스 체인 러너 복구 (run_compression_weekly_governance_chain.ps1 + P0 경로).
# 2026-05-02: 명리 독립 렌즈 → Thin JSONL 브리지 v1 (emit 스크립트·pytest; §3.6).
# 2026-05-07: GraphRAG pilot query router v1 (Track B/K observation-only; script+schema+test).
# 2026-05-12: Philosophy lane RAG pilot v1 (Track B; forbidden-substrings SSOT + CLI + pytest + Fact-Lock bundle 5c2).
# 2026-05-09: Market Myeongni overlay — P0에 회귀 pytest 추가(스키마·러너·정책은 기존 블록과 동일).
# 2026-05-09: Market Myeongni — CONTRACT 메타(MARKET_MYEONGNI_LENS_V1_CONTRACT.json) + contract path pytest (3중: 스키마·CONTRACT·회귀).
# 2026-05-09: Global orchestrator + GO stability cycle + accelerated burn-in + conditional GO+ report v2
#   (scripts only; companion / mkm_global_orchestrator *_latest.json are regenerable and often gitignored).
# 2026-05-10: AI BGM gate v1 (schema, policy, scripts/audio, pytest, CI audio-bgm-gate-smoke.yml).
# 2026-05-10: MKM Control-Integrity Golden/LoRA (schema, profile SSOT, aggregate/gate/inference/eval PS1/py, smoke pytest).
# 2026-05-10: General-rail compression benchmark (corpus JSONL, manifests, promotion chain scripts, SSOT artifacts, Multilens ultra anchor).
# 2026-05-10: Track C P1 sales kit canonical paths (mkm_ai_sales_kit_v1).
# 2026-05-10: MKM promotion gate evidence bundle + pilot report path index (G0-G11 audit JSON).
# 2026-05-11: Lens music prompt PoC M26-M30 (metric, runbook, webhook, health, dashboard bridge tests).
# 2026-05-13: Integrated governance deps-gated invoker (py + PS1 + pytest; Track C fusion / fact_lock / daily readiness).
# 2026-04-28: $required trimmed to 171 existing paths (weather triplet, eval_filter_lift,
# pre-news, and related fixtures absent in this workspace); restore entries after git merge.

$ErrorActionPreference = "Stop"
$required = @(
    "docs\final\CONSTITUTION_INFERENCE_IMPLEMENTATION_FACTS.md",
    "docs\final\MKM12_PRISM_INDEX_REGISTRY_V1.json",
    "docs\final\P0_COMMERCIALIZATION_TRACKER.md",
    "docs\final\COMPRESSION_SLA_POLICY_V1.md",
    "docs\final\COMPRESSION_INTERPRETATION_PIPELINE_FACT_LOCK_2026-03-31.md",
    "docs\final\BENCH_L1_API_LOAD_VPS_RUNBOOK.md",
    "scripts\deploy\linux\run_bench_l1_api_load_vps_fixed_fields.sh",
    "docs\NotebookLM_sources_manifest.md",
    ".cursor\rules\notebooklm-mcp-session-bridge.mdc",
    "scripts\check_notebooklm_mcp_prereqs.ps1",
    "docs\final\NOTEBOOKLM_LOG_METABOLISM_CORE_BRIDGE_POINTER_V1.md",
    "scripts\build_btrack_insight_bridge_inventory_v1.py",
    "scripts\build_btrack_insight_promotion_bridge_index_v1.py",
    "scripts\build_btrack_prophecy_score_insight_sidecar_stub_v1.py",
    "scripts\build_btrack_prophecy_score_insight_overlay_view_v1.py",
    "docs\final\schemas\btrack_prophecy_score_insight_sidecar_v1.schema.json",
    "docs\final\schemas\btrack_prophecy_score_insight_overlay_view_v1.schema.json",
    "docs\final\artifacts\btrack_prophecy_score_insight_sidecar_v1_latest.json",
    "docs\final\artifacts\btrack_prophecy_score_insight_overlay_view_v1_latest.json",
    "scripts\eval_btrack_insight_sidecar_lens_hit_agreement_v1.py",
    "docs\final\artifacts\btrack_insight_sidecar_lens_hit_agreement_v1_latest.json",
    "scripts\Run-BtrackInsightSidecarChain.ps1",
    "scripts\Run-BtrackCodebookCodepackPromotionChain.ps1",
    ".github\workflows\multilens-independent-lens-smoke.yml",
    ".github\workflows\dual-regime-integrity.yml",
    ".github\workflows\bio-sasang-nstates-rehydrate-smoke.yml",
    "scripts\build_bio_sasang_nstates_strict_comparison_rehydrate_v1.py",
    "scripts\Generate-BioSasangWeeklyReport_v1.ps1",
    "scripts\Find-BioSasangArtifactsInBackupRoots.ps1",
    "tests\test_bio_sasang_nstates_strict_comparison_rehydrate_v1.py",
    "scripts\register_btrack_insight_sidecar_chain_task.ps1",
    "scripts\register_btrack_codebook_codepack_chain_task.ps1",
    "scripts\validate_lg_washer_voice_golden_jsonl_v1.py",
    "docs\final\artifacts\lg_washer_voice_golden_train_v1.jsonl",
    "docs\final\artifacts\lg_washer_voice_golden_holdout_v1.jsonl",
    "docs\final\artifacts\lg_washer_voice_golden_split_manifest_v1.json",
    "scripts\check_codebook_codepack_drift_v1.py",
    "scripts\check_lg_washer_measurement_gate_v1.py",
    "scripts\check_lg_washer_estimation_readiness_v1.py",
    "scripts\refresh_prophecy_promotion_gates_dual_v1.py",
    "scripts\build_prophecy_live_ab_summary_from_kpi_v1.py",
    "scripts\build_defense_edge_execution_evidence_v1.py",
    "scripts\build_lg_washer_voice_golden_jsonl_v1.py",
    ".cursorrules",
    "AGENTS.md",
    "docs\final\JEMA_AI_DOMAIN_POINTER_V1.md",
    "docs\final\MKM_DOMAIN_PORTFOLIO_POINTER_V1.md",
    "docs\final\TRACK_C_IP_BUSINESS_PLAN_2026-04-17.md",
    "docs\final\PUBLIC_FACING_SECURITY_AND_IP_COPY_CHECKLIST_V1.md",
    "docs\final\MKM_HEALTH_WELLNESS_COPY_GUARDRAILS_KR_V1.md",
    "docs\final\CENTRAL_AGENT_MEMORY_V1.md",
    "README.md",
    "scripts\run_workspace_automation_health.ps1",
    "scripts\run_fact_lock_bundle.ps1",
    "projects\bitcoin-trading\AGENTS.md",
    "CLAUDE.md",
    "docs\final\LOCAL_VS_VPS_ONE_RULE_WORKFLOW.md",
    "docs\final\LOCAL_MACHINE_POINTER_V1.template.md",
    "docs\final\MKM_TRINITY_INDEX_V1.json",
    "docs\final\schemas\mkm_trinity_index_v1.schema.json",
    "tests\test_mkm_trinity_index_v1.py",
    "docs\final\NO1KMEDI_MKMLIFE_REPO_PATH_SSOT_2026-04-08.md",
    "scripts\sync_notebooklm_sources_to_mkm_data_vault.ps1",
    "scripts\run_multilens_v2_bridge_policy_snapshot.py",
    "scripts\run_waiting_queue_monthly_check.ps1",
    "projects\bitcoin-trading\ops\windows-rehearsal\DAILY_EXECUTION_INSIGHT_BRIEF_TEMPLATE.md",
    "scripts\build_daily_execution_insight_brief_v1.py",
    "scripts\Run-DailyExecutionInsightBrief_v1.ps1",
    "scripts\Register-DailyExecutionInsightBriefTask.ps1",
    "scripts\Run-AmsaengEosaMonitoringBundleTask.ps1",
    "scripts\check_amsaeng_eosa_artifact_staleness_v1.py",
    "scripts\Invoke-AmsaengEosaGovernanceCycle.ps1",
    "scripts\check_no1kmedi_internal_api_security_contract_v1.py",
    "scripts\Invoke-No1kmediInternalApiSecurityProbe_v1.ps1",
    "scripts\sign_public_event_gateway_get_hmac_v1.py",
    "tests\test_public_event_gateway_get_hmac_v1.py",
    "docs\final\artifacts\amsaeng_eosa_governance_scope_v1.json",
    "docs\final\artifacts\mkm_ops_sync_bridge_v1.json",
    "scripts\check_cross_lens_rag_notify_prereqs_v1.ps1",
    "scripts\send_cross_lens_rag_alert_v1.py",
    "scripts\build_trackc_evidence_rag_mvp_v1.py",
    "scripts\run_market_myeongni_lens_v1.py",
    "scripts\market_myeongni_overlay_engine_v1.py",
    "data\market_myeongni\market_myeongni_overlay_policy_v1.json",
    "docs\final\artifacts\schemas\market_myeongni_lens_v1.schema.json",
    "docs\final\artifacts\MARKET_MYEONGNI_LENS_V1_CONTRACT.json",
    "tests\test_market_myeongni_overlay_v1.py",
    "tests\test_market_myeongni_lens_contract_v1.py",
    "tests\test_build_daily_execution_insight_brief_v1.py",
    "tests\test_build_trackc_evidence_rag_mvp_v1.py",
    "scripts\build_mkm_trackc_ops_dashboard_v1.py",
    "tests\test_build_mkm_trackc_ops_dashboard_v1.py",
    "scripts\emit_myeongni_thin_bridge_line_v1.py",
    "tests\test_emit_myeongni_thin_bridge_line_v1.py",
    "projects\bitcoin-trading\ops\windows-rehearsal\GENERAL_PROPHECY_MONTHLY_SCHEDULER_RUNBOOK_V1.md",
    "projects\bitcoin-trading\ops\windows-rehearsal\register_fused_quant_pixel_sop_strict_check_task.ps1",
    "projects\bitcoin-trading\ops\windows-rehearsal\register_fused_quant_pixel_sop_strict_check_task_clean.ps1",
    "projects\bitcoin-trading\ops\windows-rehearsal\automation_registry.json",
    "projects\bitcoin-trading\ops\windows-rehearsal\reconcile_automation_registry.ps1",
    "tests\test_automation_registry_json_v1.py",
    "scripts\eval_prophecy_hit_rate_v1.py",
    "scripts\fetch_kospi_yfinance_csv.py",
    "tests\test_load_kospi_yf_rows.py",
    "docs\final\GENERAL_PROPHECY_SCHEMA_V1.json",
    "scripts\generate_general_prophecy_v1.py",
    "scripts\build_general_prophecy_brief.py",
    "scripts\eval_general_prophecy_brier_score.py",
    "tests\test_weather_gt_triplet_chain_smoke.py",
    "scripts\export_general_prophecy_to_jsonl.py",
    "scripts\apply_general_prophecy_registry_patches_v1.py",
    "scripts\Invoke-GeneralProphecyPatchAndExport.ps1",
    "scripts\Invoke-GeneralProphecyExportThenLora.ps1",
    "scripts\resolve_general_prophecy_question_v1.py",
    "tests\fixtures\general_prophecy_registry_sample_v1.json",
    "tests\fixtures\general_prophecy_registry_seed_5_v1.json",
    "tests\fixtures\general_prophecy_registry_brier_smoke_v1.json",
    "tests\fixtures\general_prophecy_registry_official_seed_v1.json",
    "tests\fixtures\general_prophecy_registry_macro_h2_2026_pack_v1.json",
    "tests\test_export_general_prophecy_to_jsonl.py",
    "tests\test_apply_general_prophecy_registry_patches_v1.py",
    "tests\fixtures\general_prophecy_registry_patch_sample_v1.json",
    "scripts\generate_btrack_hypothesis_prophecy_v1.py",
    "scripts\run_btrack_prophecy_contemplation_v1.py",
    "docs\final\schemas\btrack_prophecy_contemplation_v1.schema.json",
    "tests\test_run_btrack_prophecy_contemplation_v1.py",
    "tests\test_btrack_daily_hypothesis_chain_contemplation_contract_v1.py",
    "scripts\eval_prophecy_promotion_gates_v1.py",
    "scripts\fast_promotion_gate_v1.py",
    "tests\test_fast_promotion_gate_v1.py",
    "scripts\build_logos_wide_restoration.py",
    "scripts\build_btrack_prophecy_score_from_ohlcv.py",
    "scripts\build_direction_label_bar_jsonl_from_ohlcv_v1.py",
    "scripts\join_news_observation_direction_labels_walkforward_v1.py",
    "scripts\validate_news_observation_jsonl_v1.py",
    "docs\final\schemas\news_observation_v1.schema.json",
    "docs\final\schemas\direction_label_bar_v1.schema.json",
    "tests\fixtures\join_walkforward_smoke_v1.news.jsonl",
    "tests\fixtures\join_walkforward_smoke_v1.labels.jsonl",
    "scripts\run_daily_prophecy_eval_and_report.ps1",
    "scripts\report_btrack_notebooklm_jsonl_kpi.py",
    "projects\bitcoin-trading\ops\v2\tasks\run_prophecy_alignment_pytest.ps1",
    "scripts\build_myeongri_sasang_codebook_spike_v1.py",
    "scripts\spike_4grid_myeongri_compression_v1.py",
    "scripts\Run-4GridMyeongriCompressionSpikeV1.ps1",
    "tests\test_spike_4grid_myeongri_compression_v1.py",
    "data\myeongni\jijangan_lut_v1.json",
    "docs\final\schemas\jijangan_lut_v1.schema.json",
    "scripts\myeongri_jijangan_v1.py",
    "tests\test_myeongri_jijangan_v1.py",
    "data\myeongni\jijangan_ohang_weights_v1.json",
    "docs\final\artifacts\schemas\myeongni_core_vector_v1.schema.json",
    "scripts\myeongri_daewoon_v1.py",
    "scripts\myeongri_jijangan_ohang_v1.py",
    "tests\test_myeongri_jijangan_ohang_v1.py",
    "tests\test_myeongri_daewoon_v1.py",
    "data\myeongni\rule_school_mkm_4d_v1.json",
    "scripts\myeongri_rule_school_mkm_4d_v1.py",
    "tests\test_myeongri_rule_school_mkm_4d_v1.py",
    "data\myeongni\myeongni_conflict_arbitration_v1.json",
    "scripts\verify_myeongni_conflict_arbitration_edgecases_v1.py",
    "scripts\core\solar_term_jie_crossings_v1.py",
    "scripts\myeongri_qiyun_v1.py",
    "tests\test_myeongri_qiyun_v1.py",
    "scripts\myeongri_daewoon_timeline_v1.py",
    "docs\final\artifacts\schemas\myeongri_daewoon_timeline_v1.schema.json",
    "tests\test_myeongri_daewoon_timeline_v1.py",
    "docs\final\MYEONGRI_AI_INTERPRETATION_PROMPT_TEMPLATE_V1.md",
    "docs\final\KOREAN_MEDICAL_CANON_INGEST_HANDOFF_2026-03-28.md",
    "docs\final\MKM_LENS_GLOBAL_PROFILE_PROMPT_RAG_INSTRUCTIONS_DRAFT_V1.md",
    "docs\final\schemas\myeongri_ai_interpretation_envelope_v1.schema.json",
    "tests\test_myeongri_ai_interpretation_envelope_v1.py",
    "docs\final\schemas\km_physician_cds_assist_envelope_v1.schema.json",
    "tests\fixtures\km_physician_cds_assist_envelope_v1.example.json",
    "tests\test_km_physician_cds_assist_envelope_v1.py",
    "scripts\build_km_physician_cds_assist_envelope_v1.py",
    "scripts\run_km_physician_cds_assist_envelope_batch_v1.py",
    "scripts\Run-KmPhysicianCdsEnvelopeBatchWeekly_v1.ps1",
    "scripts\Register-KmPhysicianCdsEnvelopeBatchWeeklyTask.ps1",
    "tests\fixtures\km_physician_cds_assist_payload_batch_v1.example.jsonl",
    "tests\test_build_km_physician_cds_assist_envelope_v1.py",
    "tests\test_run_km_physician_cds_assist_envelope_batch_v1.py",
    "scripts\run_myeongri_ai_interpretation_pack_v1.py",
    "scripts\eval_myeongri_rule_school_macro_stub_v1.py",
    "tests\test_eval_myeongri_rule_school_macro_stub_v1.py",
    "data\market_sasang\market_sasang_lens_policy_v1.json",
    "scripts\market_sasang_lens_engine_v1.py",
    "scripts\run_market_sasang_lens_v1.py",
    "docs\final\schemas\market_sasang_lens_output_v1.schema.json",
    "docs\final\artifacts\MARKET_SASANG_LENS_V1_CONTRACT.json",
    "tests\test_market_sasang_lens_v1.py",
    "scripts\track_b_commander_gate_v1.py",
    "data\logos\logos_track_b_commander_deep_report_envelope_v1.json",
    "scripts\run_logos_track_b_commander_deep_report_v1.py",
    "scripts\materialize_logos_track_b_commander_deep_report_v1.py",
    "docs\final\schemas\logos_track_b_commander_deep_report_v1.schema.json",
    "docs\final\artifacts\LOGOS_TRACK_B_COMMANDER_DEEP_REPORT_V1_CONTRACT.json",
    "tests\test_logos_track_b_commander_deep_report_v1.py",
    "scripts\run_manseryeok_bot_v1.py",
    "tests\test_run_manseryeok_bot_v1.py",
    "data\myeongni\myeongni_track_b_commander_report_envelope_v1.json",
    "scripts\build_myeongni_track_b_commander_report_v1.py",
    "tests\test_build_myeongni_track_b_commander_report_v1.py",
    "scripts\core\track_source_guard.py",
    "scripts\core\sovereign_jsonl.py",
    "scripts\spike_sovereign_token_saving.py",
    "scripts\spike_sovereign_vocab_efficiency.py",
    "tests\test_track_source_guard.py",
    "tests\test_sovereign_jsonl.py",
    "tests\test_spike_sovereign_token_saving_v1.py",
    "tests\test_sovereign_efficiency.py",
    "data\track_a_shadow\conversations_sample_v1.jsonl",
    "scripts\core\domain_router.py",
    "scripts\core\multilens_bridge_policy_env.py",
    "scripts\run_prophecy_restoration_spike.py",
    "tests\test_prophecy_restoration_spike.py",
    "docs\final\artifacts\prophecy_overlay_prior_threshold_recommended_latest.json",
    "docs\final\artifacts\prophecy_prior_threshold_sweep_summary_latest.json",
    "codebook\shards\zone_a_scm.json",
    "codebook\shards\zone_b_timing.json",
    "codebook\shards\zone_c_hangul.json",
    "codebook\shards\zone_d_ssot.json",
    "codebook\shards\zone_e_finance.json",
    "codebook\shards\zone_f_code.json",
    "codebook\shards\zone_g_health.json",
    "codebook\shards\zone_h_legacy.json",
    "docs\final\master_codebook_dual_track.multidomain_1000.json",
    "docs\final\openapi_token_compression_stub_v1.yaml",
    "scripts\compression_token_api_v2_stub.py",
    "scripts\Serve-CompressionV2Explorer.ps1",
    "scripts\Start-CompressionV2ExplorerDemo.ps1",
    "projects\bitcoin-trading\ops\windows-rehearsal\jemaai-cloud-mvp\compression_v2_explorer.html",
    "projects\bitcoin-trading\ops\windows-rehearsal\jemaai-cloud-mvp\public_showroom_board_minimal.html",
    "docs\final\schemas\mkm_user_context_v1.schema.json",
    "docs\final\schemas\mkm_compressed_payload_v1.schema.json",
    "scripts\check_news_label_join_temporal_v1.py",
    "scripts\build_news_observation_jsonl_from_csv_v1.py",
    "scripts\Run-NewsObservationContractSmoke.ps1",
    "scripts\Run-BTrackDomainFeedbackSmoke.ps1",
    "scripts\dump_mcp_tool_inventory.py",
    "scripts\mkm_unified_mcp.py",
    "rag_server\mcp_server.py",
    "rag_server\cursor-mcp.env",
    "scripts\requirements-mkm-mcp.txt",
    "docs\final\artifacts\mkm_mcp_tool_audit_v1.json",
    "docs\final\artifacts\MKM_MCP_STDIO_POINTER_V1.json",
    "data\personalization\mkm_user_context_v1.sample.json",
    "docs\final\COMPRESSION_12M_LEARNINGS_AND_TRACKB_PLAYBOOK_2026-04-08.md",
    "scripts\run_compression_weekly_governance_chain.ps1",
    "scripts\build_compression_weekly_governance_report.py",
    "scripts\Register-CompressionWeeklyGovernanceTask.ps1",
    "scripts\bench_l1_api_load.py",
    "docs\final\artifacts\bench_l1_api_load_latest.json",
    "scripts\run_l1_inverse_decoder_spike_test.py",
    "scripts\l1_side_channel_wire_codec.py",
    "scripts\run_l1_permutation_channel_integrated_spike.py",
    "docs\final\artifacts\l1_inverse_decoder_spike_test_summary_latest.json",
    "docs\final\artifacts\l1_permutation_channel_integrated_spike_latest.json",
    "scripts\report_trackb_quaternion_two_stage_gate.py",
    "docs\final\artifacts\trackb_quaternion_order_experiment_v1.json",
    "docs\final\artifacts\trackb_quaternion_order_stress_v1.json",
    "docs\final\artifacts\trackb_quaternion_generalization_v1.json",
    "docs\final\artifacts\trackb_quaternion_two_stage_gate_v2.json",
    "scripts\build_trackb_promotion_precheck_draft_v1.py",
    "scripts\experimental\codebook_runtime_pack\build_report_schema_v2_quality_alert.py",
    "scripts\experimental\codebook_runtime_pack\build_report_schema_v2_label_kpi.py",
    "scripts\spec_bio_sample_paper_snp_join_gate_v1.py",
    "scripts\apply_bio_paper_snp_sidecar_to_samples_v1.py",
    "scripts\export_bio_measured_labels_paper_snp_sidecar_v1.py",
    "scripts\run_bio_paper_snp_sidecar_export_and_apply_v1.py",
    "scripts\export_bio_sample_paper_pmid_mapping_from_cohort_v1.py",
    "scripts\run_bio_epmc_catalog_and_label_merge_v1.py",
    "docs\final\artifacts\bio_measured_labels_paper_snp_sidecar_v1.json",
    "docs\final\artifacts\bio_sample_paper_pmid_mapping_template_v1.csv",
    "tests\test_bio_paper_snp_join_chain_smoke_v1.py",
    "tests\test_run_bio_paper_snp_sidecar_export_and_apply_v1_cli.py",
    "tests\test_run_bio_epmc_catalog_and_label_merge_v1_cli.py",
    "tests\test_check_bio_genotype_paper_snp_overlap_v1.py",
    "tests\test_normalize_bio_genotype_long_v1.py",
    "tests\test_build_bio_dna_promotion_readiness_v1.py",
    "tests\test_run_bio_dna_readiness_chain_v1.py",
    "tests\test_run_bio_dna_promotion_threshold_sweep_v1.py",
    "tests\fixtures\bio_paper_snp_join_smoke_samples_v1.csv",
    "tests\fixtures\bio_paper_snp_join_smoke_mapping_v1.csv",
    "tests\fixtures\bio_genotype_rsid_smoke_v1.csv",
    ".github\workflows\bio-paper-snp-sidecar-smoke.yml",
    "scripts\Run-BioPaperSnpSidecarExportAndApply.ps1",
    "scripts\check_bio_paper_snp_mapping_coverage_v1.py",
    "scripts\check_bio_genotype_paper_snp_overlap_v1.py",
    "scripts\normalize_bio_genotype_long_v1.py",
    "scripts\build_bio_dna_promotion_readiness_v1.py",
    "scripts\run_bio_dna_readiness_chain_v1.py",
    "scripts\run_bio_dna_promotion_threshold_sweep_v1.py",
    "codebook\policies\slack_fact_safe_mention_routing_v1.json",
    "scripts\run_aramaic_mvp_chain_v1.ps1",
    "scripts\run_two_track_submission_pack_v1.ps1",
    "scripts\build_two_track_submission_evidence_bundle_v1.py",
    "scripts\build_two_track_submission_draft_v1.py",
    "scripts\build_two_track_submission_camera_ready_v1.py",
    "tests\test_build_two_track_submission_evidence_bundle_v1.py",
    "tests\test_build_two_track_submission_draft_v1.py",
    "tests\test_build_two_track_submission_camera_ready_v1.py",
    "scripts\extract_aramaic_core_corpus_v1.py",
    "tests\test_extract_aramaic_core_corpus_v1.py",
    "scripts\run_truthfulqa_ab_benchmark_v1.py",
    "tests\test_run_truthfulqa_ab_benchmark_v1.py",
    "scripts\check_truthfulqa_ab_gate_v1.py",
    "tests\test_check_truthfulqa_ab_gate_v1.py",
    "scripts\Run-TruthfulQAReproBundleV1.ps1",
    "tests\test_run_truthfulqa_repro_bundle_v1.py",
    "docs\final\schemas\sasang_interpretive_insight_bundle_v1.schema.json",
    "docs\final\artifacts\SASANG_INTERPRETIVE_INSIGHT_BUNDLE_V1_CONTRACT.json",
    "scripts\build_sasang_interpretive_insight_bundle_v1.py",
    "docs\final\artifacts\sasang_interpretive_insight_bundle_v1_latest.json",
    "tests\test_sasang_interpretive_insight_bundle_v1.py",
    "docs\final\artifacts\LOGOS_VECTOR_INDEX_ANN_LITE_BUILD_REPORT_V1_CONTRACT.json",
    "docs\final\schemas\logos_vector_index_ann_lite_build_report_v1.schema.json",
    "scripts\build_logos_vector_index_ann_lite_v1.py",
    "scripts\logos_vector_hash_stub_v1.py",
    "scripts\query_logos_vector_index_ann_lite_v1.py",
    "docs\final\schemas\logos_vector_ann_lite_query_result_v1.schema.json",
    "tests\test_logos_vector_index_ann_lite_v1.py",
    "docs\final\schemas\btrack_yang_2015_style_metrics_v1.schema.json",
    "docs\final\schemas\myeongni_celebrity_hit_rate_v1.schema.json",
    "scripts\btrack_yang_2015_style_metrics_v1.py",
    "scripts\run_myeongni_celebrity_benchmark_v1.py",
    "scripts\run_saju_global_birth_v1.py",
    "scripts\myeongri_core_v2_upgrade.py",
    "data\myeongni\celebrity_saju_benchmark_v1.jsonl",
    "data\myeongni\paper_contract_maps\yang_2015_four_pillars_personality_map_v1.json",
    "tests\test_btrack_yang_2015_style_metrics_v1.py",
    "tests\test_myeongni_paper_contract_map_v1.py",
    "tests\test_run_myeongni_celebrity_benchmark_v1.py",
    "scripts\fetch_europepmc_sasang_saju_literature_catalog_v1.py",
    "scripts\ingest_curated_saju_joint_v1.py",
    "scripts\validate_sasang_saju_joint_benchmark_jsonl_v1.py",
    "data\myeongni\curated_saju_joint_v1.jsonl",
    "docs\final\schemas\curated_saju_joint_input_row_v1.schema.json",
    "tests\test_ingest_curated_saju_joint_v1.py",
    "data\myeongni\16_STATE_MASTER_PROBE_v1.json",
    "scripts\check_curated_saju_joint_staleness_v1.py",
    "tests\test_check_curated_saju_joint_staleness_v1.py",
    "tests\test_yang_2015_btrack_json_schema_v1.py",
    "scripts\run_graphrag_pilot_router_v1.py",
    "docs\final\schemas\graphrag_pilot_router_v1.schema.json",
    "tests\test_run_graphrag_pilot_router_v1.py",
    "scripts\philosophy_lane_rag_pilot_v1.py",
    "scripts\run_philosophy_lane_rag_pilot_v1.ps1",
    "docs\final\artifacts\schemas\philosophy_lane_rag_pilot_forbidden_substrings_v1.json",
    "tests\test_philosophy_lane_rag_pilot_v1.py",
    "scripts\Invoke-MaxProphecyBurst_v1.ps1",
    "scripts\Invoke-LabVpsBtrackM31Smoke_v1.ps1",
    "scripts\vps_bitcoin_live_hygiene_reset_v1.sh",
    "scripts\vps_mkm_lab_hygiene_reset_v1.sh",
    "scripts\Invoke-MkmlifeVpsGitProbe.ps1",
    "scripts\mkm_global_orchestrator_v1.py",
    "scripts\apply_mkm_global_orchestrator_policy_profile_v1.py",
    "scripts\check_mkm_orchestrator_go_stability_v1.py",
    "scripts\run_mkm_orchestrator_go_stability_cycle_v1.ps1",
    "scripts\run_mkm_orchestrator_accelerated_burnin_v1.ps1",
    "scripts\build_mkm_conditional_go_plus_report_v2.py",
    "scripts\Run-TradingGuardianBundleTask.ps1",
    "scripts\Run-MkmWeeklyOperationalEvidenceCadence.ps1",
    ".github\workflows\audio-bgm-gate-smoke.yml",
    "docs\final\schemas\audio_bgm_gate_report_v1.schema.json",
    "docs\final\schemas\audio_bgm_gate_report_v1.example.json",
    "policies\audio_copyright_field.json",
    "scripts\audio\evaluate_audio_gate.py",
    "scripts\audio\run_bgm_generation_batch.py",
    "scripts\audio\generate_placeholder_wav.py",
    "scripts\audio\external_generator_stub_v1.py",
    "scripts\audio\external_generator_template_v1.py",
    "scripts\audio\gemini_bgm_seed_expand_v1.py",
    "scripts\audio\gemini_placeholder_external_generator_v1.py",
    "scripts\audio\tone_external_generator_v1.py",
    "scripts\audio\expand_tone_external_generator_v1.py",
    "scripts\audio\ffmpeg_bed_external_generator_v1.py",
    "scripts\audio\check_audio_gate_optional_deps_v1.py",
    "scripts\Run-AudioBgmGeminiExternalChain_v1.ps1",
    "scripts\Run-AudioBgmEconomyChain_v1.ps1",
    "scripts\run_lens_music_gematria.py",
    "scripts\run_lens_music_gematria_gate_chain_v1.py",
    "data\audio\seeds\tension_sasang_01.example.json",
    "data\audio\seeds\calm_taeeum_01.example.json",
    "docs\final\schemas\sasang_music_mapping_v1.schema.json",
    "docs\final\schemas\sasang_music_mapping_v1.example.json",
    "docs\final\schemas\lens_music_gematria_seed_trace_v1.schema.json",
    "docs\final\schemas\lens_music_gematria_seed_trace_v1.example.json",
    "tests\test_lens_music_gematria_seed_trace_schema_v1.py",
    "docs\final\schemas\lens_music_rag_metabolism_drift_v1.schema.json",
    "docs\final\schemas\lens_music_m31_audit_trail_v1.schema.json",
    "docs\final\schemas\lens_music_m31_audit_trail_v1.example.json",
    "tests\test_lens_music_m31_audit_trail_schema_v1.py",
    "docs\final\schemas\sasang_emotion_mapping_v1.schema.json",
    "docs\final\schemas\sasang_emotion_mapping_v1.example.json",
    "docs\final\schemas\va_trajectory_log_v1.schema.json",
    "docs\final\schemas\va_trajectory_log_v1.example.json",
    "docs\final\schemas\va_cooldown_policy_v1.schema.json",
    "docs\final\schemas\va_cooldown_policy_v1.example.json",
    "docs\final\schemas\va_cooldown_event_v1.schema.json",
    "docs\final\schemas\va_cooldown_event_v1.example.json",
    "scripts\build_lens_emotion_va_trajectory_v1.py",
    "tests\test_va_trajectory_log_v1.py",
    "tests\test_va_cooldown_schema_v1.py",
    "docs\final\schemas\cross_lens_fusion_report_v1.schema.json",
    "docs\final\schemas\cross_lens_fusion_report_v1.example.json",
    "scripts\build_cross_lens_fusion_report_v1.py",
    "tests\fixtures\cross_lens_fusion_candidates_sample_v1.json",
    "tests\test_cross_lens_fusion_report_v1.py",
    "docs\final\schemas\fusion_control_integrity_audit_v1.schema.json",
    "docs\final\schemas\fusion_control_integrity_audit_v1.example.json",
    "scripts\build_fusion_control_integrity_audit_v1.py",
    "tests\fixtures\fusion_control_integrity_va_sample_v1.json",
    "tests\fixtures\fusion_control_integrity_cooldown_event_sample_v1.json",
    "tests\fixtures\fusion_control_integrity_fusion_report_sample_v1.json",
    "tests\test_fusion_control_integrity_audit_v1.py",
    "tests\test_va_fusion_control_integrity_chain_v1.py",
    "tests\test_va_fusion_policy_golden_v1.py",
    "tests\fixtures\va_fusion_policy_golden_v1.json",
    "scripts\Run-VaFusionControlIntegrityChain_v1.ps1",
    "scripts\Register-VaFusionControlIntegrityDailyTask.ps1",
    "docs\final\schemas\lens_music_internal_eval_session_v1.schema.json",
    "docs\final\schemas\lens_music_internal_eval_session_v1.example.json",
    "docs\final\schemas\lens_music_symbolic_audio_promotion_gate_v1.schema.json",
    "docs\final\schemas\lens_music_symbolic_audio_promotion_gate_v1.example.json",
    "scripts\check_lens_music_symbolic_audio_promotion_gate_v1.py",
    "scripts\Run-LensMusicPromotionGateStagingStrict_v1.ps1",
    "scripts\build_lens_music_hormone_trend_v1.py",
    "scripts\build_integrated_governance_v1.py",
    "scripts\invoke_build_integrated_governance_if_deps_present_v1.py",
    "scripts\Invoke-BuildIntegratedGovernanceIfDepsPresent_v1.ps1",
    "tests\test_build_integrated_governance_m31_digest_v1.py",
    "tests\test_invoke_build_integrated_governance_if_deps_present_v1.py",
    "docs\final\schemas\lens_music_m31_operational_digest_v1.schema.json",
    "docs\final\schemas\lens_music_m31_operational_digest_v1.example.json",
    "docs\final\artifacts\integrated_governance_config_v1.json",
    "scripts\dispatch_lens_music_hormone_trend_webhook_v1.py",
    "scripts\validate_lens_music_internal_eval_jsonl_v1.py",
    "scripts\run_lens_music_prompt_poc_metric_v1.py",
    "scripts\run_btrack_logos_music_overlay_poc_v1.py",
    "scripts\build_lens_music_prompt_poc_runbook_v1.py",
    "scripts\dispatch_lens_music_prompt_poc_runbook_webhook_v1.py",
    "scripts\build_lens_music_prompt_runbook_webhook_health_summary_v1.py",
    "scripts\Invoke-McpHygieneProbe.ps1",
    "scripts\Invoke-VpsOpsSmoke_v1.ps1",
    "scripts\Invoke-SafeOpsSurfaceCheck.ps1",
    "scripts\Register-SafeOpsSurfaceCheckTask.ps1",
    "scripts\Dedupe-MkmControlIntegrityInferenceBatch.ps1",
    "scripts\Invoke-LiveSyncHeartbeatCheck.ps1",
    "scripts\Invoke-LiveSyncHeartbeatPull.ps1",
    "scripts\Register-LiveSyncHeartbeatPullTask.ps1",
    "scripts\Deploy-LiveSyncHeartbeatToVps.ps1",
    "scripts\linux\live_sync_push_heartbeat_snippet.sh",
    "docs\final\artifacts\schemas\live_sync_heartbeat_v1.schema.json",
    "docs\final\artifacts\fixtures\live_sync_heartbeat_v1.example.json",
    "scripts\Register-McpHygieneProbeDailyTask.ps1",
    "tests\test_audio_bgm_gate_report_v1.py",
    "tests\test_sasang_music_mapping_schema_v1.py",
    "tests\test_sasang_emotion_mapping_schema_v1.py",
    "tests\test_lens_music_internal_eval_schema_v1.py",
    "tests\test_lens_music_symbolic_audio_promotion_gate_v1.py",
    "tests\test_build_lens_music_hormone_trend_v1.py",
    "tests\test_dispatch_lens_music_hormone_trend_webhook_v1.py",
    "tests\test_run_lens_music_gematria_v1.py",
    "tests\test_lens_music_gate_chain_v1.py",
    "tests\test_validate_lens_music_internal_eval_jsonl_v1.py",
    "tests\fixtures\lens_music_internal_eval_sessions_sample_v1.jsonl",
    "tests\test_run_lens_music_prompt_poc_metric_v1.py",
    "tests\test_run_btrack_logos_music_overlay_poc_v1.py",
    "tests\test_build_lens_music_prompt_poc_runbook_v1.py",
    "tests\test_dispatch_lens_music_prompt_poc_runbook_webhook_v1.py",
    "tests\test_build_lens_music_prompt_runbook_webhook_health_summary_v1.py",
    "tests\fixtures\lens_music_prompt_poc_pairs_sample_v1.jsonl",
    "tests\fixtures\lens_music_prompt_runbook_webhook_history_sample_v1.jsonl",
    "docs\final\schemas\mkm_control_integrity_golden_set_v1.schema.json",
    "docs\final\artifacts\mkm_control_integrity_lora_model_profiles_v1.json",
    "scripts\aggregate_mkm_control_integrity_eval_holdout_v1.py",
    "scripts\check_mkm_control_integrity_promotion_gate_v1.py",
    "scripts\run_mkm_control_integrity_inference_batch_v1.py",
    "scripts\evaluate_mkm_control_integrity_lora_predictions_v1.py",
    "scripts\Run-MkmControlIntegrityTrainInferEval.ps1",
    "scripts\Run-MkmControlIntegrityHoldoutEvalSuite.ps1",
    "scripts\Run-MkmControlIntegrityModelProfileABC.ps1",
    "scripts\build_mkm_control_integrity_model_profile_abc_comparison_v1.py",
    "tests\test_mkm_control_integrity_pipeline_smoke_v1.py",
    "scripts\build_general_compression_eval_input.py",
    "scripts\run_general_compression_ab.py",
    "scripts\run_general_compression_sweep.py",
    "scripts\validate_general_compression_bundle.py",
    "scripts\report_general_compression_kpi_gate.py",
    "scripts\report_general_compression_failure_taxonomy.py",
    "scripts\report_general_compression_domain_guard_gate.py",
    "scripts\report_general_compression_token_loss_aggregate.py",
    "scripts\split_general_compression_holdout_v1.py",
    "scripts\build_general_compression_split_manifests_v1.py",
    "scripts\apply_general_compression_sweep_anchor_to_ultra_decision_v1.py",
    "scripts\Run-GeneralCompressionChain.ps1",
    "scripts\Run-GeneralCompressionPromotionChain.ps1",
    "data\general_compression\meeting_v1.jsonl",
    "data\general_compression\policy_legal_lite_v1.jsonl",
    "data\general_compression\support_faq_v1.jsonl",
    "docs\final\artifacts\general_compression_benchmark_manifest_v1.json",
    "docs\final\artifacts\general_compression_benchmark_manifest_train_v1.json",
    "docs\final\artifacts\general_compression_benchmark_manifest_holdout_v1.json",
    "docs\final\artifacts\general_compression_holdout_split_report_v1.json",
    "docs\final\artifacts\general_compression_restore_stress_v1.json",
    "docs\final\artifacts\general_compression_repro_command_v1.txt",
    "docs\final\artifacts\general_compression_eval_input_v1.json",
    "docs\final\artifacts\general_compression_eval_input_holdout_v1.json",
    "docs\final\artifacts\general_compression_sweep_result_v1.json",
    "docs\final\artifacts\general_compression_ab_result_summary_v1.json",
    "docs\final\artifacts\general_compression_ab_holdout_result_summary_v1.json",
    "docs\final\artifacts\general_compression_kpi_gate_v2.json",
    "docs\final\artifacts\general_compression_90pct_failure_taxonomy_v1.json",
    "docs\final\artifacts\general_compression_domain_guard_gate_v1.json",
    "docs\final\artifacts\general_compression_token_loss_aggregate_v1.json",
    "docs\final\artifacts\general_compression_ab_result_timeseries_v1.csv",
    "docs\final\artifacts\MULTILENS_ULTRA_COMPRESSION_DECISION_V1.json",
    "docs\final\artifacts\MULTILENS_ULTRA_COMPRESSION_ACTIVE_REPORT_V1.json",
    "tests\test_build_general_compression_eval_input_smoke_v1.py",
    "tests\test_validate_general_compression_bundle_v1.py",
    "tests\test_split_general_compression_holdout_smoke_v1.py",
    "tests\test_build_general_compression_split_manifests_smoke_v1.py",
    "tests\fixtures\general_compression_bundle_minimal_v1\manifest_go.json",
    "tests\fixtures\general_compression_bundle_minimal_v1\manifest_no_go.json",
    "docs\final\artifacts\mkm_ai_sales_kit_v1\MKM_AI_LANDING_COPY_V1.md",
    "docs\final\artifacts\mkm_ai_sales_kit_v1\MKM_AI_API_BRANDING_BRIDGE_V1.md",
    "docs\final\artifacts\mkm_ai_sales_kit_v1\MKM_AI_FACTSAFE_NUMBERS_V1.md",
    "docs\final\artifacts\mkm_ai_sales_kit_v1\MKM_AI_SALES_KIT_STRUCTURE_V1.json",
    "scripts\core\state16_interface.py",
    "docs\final\STATE16_INTERFACE_INSERTION_CONTRACT_2026-03-31.md",
    "scripts\build_mkm_promotion_gate_evidence_bundle_v1.py",
    "docs\final\artifacts\mkm_promotion_gate_evidence_bundle_v1.json",
    "docs\final\LORA_PACK_V0_DOD_V1.md",
    "docs\final\schemas\myeongri_deterministic_lora_golden_set_v1.schema.json",
    "scripts\prep_myeongri_deterministic_lora_golden_v1.py",
    "scripts\build_myeongri_deterministic_lora_golden_bulk_v1.py",
    "tests\fixtures\myeongri_deterministic_lora_golden_sample_v1.jsonl",
    "docs\final\artifacts\myeongri_deterministic_lora_model_profiles_v1.json",
    "scripts\eval_myeongri_deterministic_lora_golden_fit_v1.py",
    "storage\adapters\myeongri_deterministic_lora_v0\.gitkeep",
    "tests\test_myeongri_deterministic_lora_golden_set_schema_v1.py",
    "tests\test_build_myeongri_deterministic_lora_golden_bulk_v1.py",
    "tests\test_eval_myeongri_deterministic_lora_golden_fit_v1.py",
    "tests\test_myeongri_deterministic_lora_pack_copy_guardrails_v1.py",
    "scripts\run_track_a_conversational_cost_simulation.py",
    "scripts\run_track_a_shadow_corpus_eval.py",
    "scripts\run_track_a_metering_summary.py",
    "scripts\run_track_a_metering_weekly_report.py",
    "scripts\check_track_a_metering_band_gate.py",
    "scripts\build_track_a_signal_light_report.py",
    "scripts\run_track_a_commercialization_daily_chain.ps1",
    "scripts\Run-TrackAShadowJsonlSample.ps1",
    "scripts\Run-TrackAMeteringSummary.ps1",
    "scripts\Run-TrackAMeteringWeeklyReport.ps1",
    "scripts\Register-TrackACommercializationDailyTask.ps1",
    "scripts\Verify-TrackACommercializationDailyScheduledTask_v1.ps1",
    "tests\fixtures\track_a_metering_log_smoke_v1.jsonl",
    "docs\final\artifacts\MKM_AI_COMPRESSION_PILOT_REPORT_PATHS_V1.json"
)

$missing = @()
foreach ($rel in $required) {
    $normRel = $rel.Replace('\', [System.IO.Path]::DirectorySeparatorChar)
    $p = Join-Path $WorkspaceRoot $normRel
    if (-not (Test-Path -LiteralPath $p)) {
        $missing += $rel
    }
}

if ($missing.Count -gt 0) {
    Write-Host "FAIL: missing paths (see P0_COMMERCIALIZATION_TRACKER.md '증거 경로'):" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  $_" }
    exit 1
}

Write-Host "OK: P0/CONSTITUTION gate paths present ($($required.Count) checked)."

$optionalQualityArtifacts = @(
    "docs\final\artifacts\report_schema_v2_quality_alert_latest.json",
    "docs\final\artifacts\report_schema_v2_label_kpi_latest.json",
    "docs\final\artifacts\report_schema_v2_latest.json",
    "docs\final\artifacts\truthfulqa_ab_benchmark_latest.json",
    "docs\final\artifacts\truthfulqa_generation_ab_benchmark_latest.json",
    "docs\final\artifacts\truthfulqa_ab_gate_latest.json"
)
$missingOptional = @()
foreach ($rel in $optionalQualityArtifacts) {
    $normRel = $rel.Replace('\', [System.IO.Path]::DirectorySeparatorChar)
    $p = Join-Path $WorkspaceRoot $normRel
    if (-not (Test-Path -LiteralPath $p)) {
        $missingOptional += $rel
    }
}
if ($missingOptional.Count -gt 0) {
    Write-Host "WARN: optional artifacts missing (report_schema_v2 or TruthfulQA benchmark outputs):" -ForegroundColor Yellow
    $missingOptional | ForEach-Object { Write-Host "  $_" }
}

exit 0
